pipeline {
    agent any

    environment {
        DOCKER_IMAGE = "admincbo/webapp-cicd"
        CONTAINER_NAME = "webapp_cicd"
        APP_PORT = "3003"
    }

    stages {

        stage('Checkout Source') {
            steps {
                checkout scm
            }
        }

        stage('Build Docker Image') {
            steps {
                dir('01_source_code/webapp') {
                    sh '''
                      docker build \
                      -t $DOCKER_IMAGE:latest \
                      -t $DOCKER_IMAGE:${BUILD_NUMBER} .
                    '''
                }
            }
        }

        stage('Docker Login') {
            steps {
                withCredentials([usernamePassword(
                    credentialsId: 'dockerhub-creds',
                    usernameVariable: 'DOCKER_USER',
                    passwordVariable: 'DOCKER_PASS'
                )]) {
                    sh '''
                      echo "$DOCKER_PASS" | docker login -u "$DOCKER_USER" --password-stdin
                    '''
                }
            }
        }

        stage('Push Image to DockerHub') {
            steps {
                sh '''
                  docker push $DOCKER_IMAGE:latest
                  docker push $DOCKER_IMAGE:${BUILD_NUMBER}
                '''
            }
        }
        stage('Deploy Container') {
             steps {
                sh '''
                    echo "Stopping old container if exists..."
                    docker stop webapp_cicd || true
                    docker rm webapp_cicd || true

                    echo "Pulling new image..."
                    docker pull $DOCKER_IMAGE:latest

                    echo "Running new container..."
                    docker run -d \
                        --name webapp_cicd \
                        -p 3003:3003 \
                        --restart unless-stopped \
                        $DOCKER_IMAGE:latest
               '''
          }
       }
    }

    post {
        success {
            echo "✅ Day 57: Image pushed to DockerHub successfully"
        }
    }
}