pipeline {
    agent any

    environment {
        DOCKER_IMAGE = "admincbo/webapp-cicd"
    }

    stages {

        stage('Checkout Source') {
            steps {
                checkout scm
            }
        }

        stage('Build Docker Image') {
            steps {
                dir('01_source_code/webapp') {
                    sh '''
                      docker build \
                      -t $DOCKER_IMAGE:latest \
                      -t $DOCKER_IMAGE:${BUILD_NUMBER} .
                    '''
                }
            }
        }

        stage('Docker Login') {
            steps {
                withCredentials([usernamePassword(
                    credentialsId: 'dockerhub-creds',
                    usernameVariable: 'DOCKER_USER',
                    passwordVariable: 'DOCKER_PASS'
                )]) {
                    sh '''
                      echo "$DOCKER_PASS" | docker login -u "$DOCKER_USER" --password-stdin
                    '''
                }
            }
        }

        stage('Push Image to DockerHub') {
            steps {
                sh '''
                  docker push $DOCKER_IMAGE:latest
                  docker push $DOCKER_IMAGE:${BUILD_NUMBER}
                '''
            }
        }

    }

    post {
        success {
            echo "✅ Day 57: Image pushed to DockerHub successfully"
        }
    }
}
